from enum import Enum


class InvalidCause(Enum):
    """
    Enumeration of possible causes of invalid trials in TMT.
    """

    CUT_CRITERIA_ERROR = "CUT_CRITERIA_ERROR"
    UNKNOWN_ERROR = "UNKNOWN_ERROR"
    UNDER_CORRECT_TARGETS_MINIMUM = "UNDER_CORRECT_TARGETS_MINIMUM"
    INVALID_LENGTH = "INVALID_LENGTH"
    INVALID_START_CONFIGURATION = "INVALID_START_CONFIGURATION"
    INVALID_MODEL = "INVALID_MODEL"
    UNABLE_TO_DETERMINE_START = "UNABLE_DETERMINE_START"

